version: '3.4'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: javasynth
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    container_name: javasynth-api
    build: .
    environment:
      - DB="mongodb://db/${mongooseBaseName}-development"
    command: yarn start
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4741:4741"
    depends_on:
      - db
volumes:
  mongodb_data_container: